### ISSUE TITLE
class

### ISSUE THREAD

**Issue by vvoovv** [vvoovv/pml#13]
I am going to introduce the concept of _class_. It's better to explain it with an example.

PML:
```css
facade{
    class: front_facade;
}
```
It means that a texture or a mesh of class _front_facade_ should be looked up in the list of assets and applied to the _facade_ as whole. There is no need to specify the content of the _facade_ via the _markup_.
